test:
  path: /test
  defaults: { _controller: AppBundle:Api:test}
  methods: [GET, OPTIONS]

repository:
  path: /repository
  defaults: { _controller: AppBundle:Api:repository}
  methods: [GET, OPTIONS]