test:
  path: /test
  defaults: { _controller: AppBundle:Api:test}
  methods: [GET, OPTIONS]

month:
    path: /month/{month}
    defaults: { _controller: AppBundle:Api:getByMonth}
    methods: [GET, OPTIONS]

day_month:
    path: /month-day/{month}/{day}
    defaults: { _controller: AppBundle:Api:getByMonthDay}
    methods: [GET, OPTIONS]

today:
    path: /today
    defaults: { _controller: AppBundle:Api:getToday}
    methods: [GET, OPTIONS]

main:
    path: /
    defaults: { _controller: AppBundle:Api:getToday}
    methods: [GET, OPTIONS]

random:
    path: /random
    defaults: { _controller: AppBundle:Api:getTodayRandom}
    methods: [GET, OPTIONS]