test:
  path: /test
  defaults: { _controller: AppBundle:Api:test}
  methods: [GET, OPTIONS]

month:
    path: /month/{month}
    defaults: { _controller: AppBundle:Api:getByMonth}
    methods: [GET, OPTIONS]

day_month:
    path: /month-day/{month}/{day}
    defaults: { _controller: AppBundle:Api:getByMonthDay}
    methods: [GET, OPTIONS]

today:
    path: /today
    defaults: { _controller: AppBundle:Api:getToday}
    methods: [GET, OPTIONS]

main:
    path: /
    defaults: { _controller: AppBundle:Api:getToday}
    methods: [GET, OPTIONS]

random:
    path: /random
    defaults: { _controller: AppBundle:Api:getTodayRandom}
    methods: [GET, OPTIONS]

event_create:
    path: /event
    defaults: {_controller: AppBundle:Api:create}
    methods: [POST, OPTIONS]

create:
    path: /create
    defaults: {_controller: AppBundle:Api:create}
    methods: [POST, OPTIONS]

comment_create:
    path: /chat/{chatId}/comment
    defaults: {_controller: AppBundle:Comment:create}
    methods: [POST, OPTIONS]
